# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9846bf7f38a33e33058d9bfcb3225c238a74ddc6892ff6c75904baa75bcb65d56698355d5beb4ab744f947862ea1db21fbd12df7cb2f04417fc38797d0fac950

test:
  secret_key_base: ede5641875cec412aee8c37a176e4e19dcb1fe62c3556bc2b6eb7b92fcf4f85742f9ca3bcf9c79cc7f01231e053b76d951f6b62ca69f1d36cbc09298a6fb234b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
